const { fontFamily } = require("tailwindcss/defaultTheme")

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["app/**/*.{ts,tsx}", "components/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        forest: {
          DEFAULT: "#059669",
          50: "#F6FBF9",
          100: "#DFF2EC",
          200: "#B0DED0",
          300: "#81CAB3",
          400: "#50B596",
          500: "#059669",
          600: "#04825B",
          700: "#046C4C",
          800: "#145041",
          900: "#002A24",
        },
        autumn: {
          DEFAULT: "#DB6300",
          50: "#FEF9F5",
          100: "#FAEBDE",
          200: "#F4CDAE",
          300: "#EDAF7D",
          400: "#E5904A",
          500: "#DB6300",
          600: "#BA5400",
          700: "#9B4600",
          800: "#743500",
          900: "#381900",
        },
        rowan: {
          DEFAULT: "#DF514B",
          50: "#FEF9F8",
          100: "#FBEAE9",
          200: "#F5CAC9",
          300: "#EFABA8",
          400: "#E98A86",
          500: "#DF514B",
          600: "#D13A34",
          700: "#AE312C",
          800: "#832521",
          900: "#401210",
        },
        cassia: {
          DEFAULT: "#B27C16",
          50: "#FFF9EE",
          100: "#FFECC5",
          200: "#FFCD6A",
          300: "#FBAC11",
          400: "#DB970F",
          500: "#B27C16",
          600: "#99690A",
          700: "#7F5708",
          800: "#5F4106",
          900: "#312306",
        },
        sky: {
          DEFAULT: "#1E85D9",
          50: "#F5FBFF",
          100: "#DEF0FF",
          200: "#ACDAFF",
          300: "#79C3FF",
          400: "#42AAFF",
          500: "#1E85D9",
          600: "#1A75C0",
          700: "#1662A0",
          800: "#104978",
          900: "#082339",
        },
        wood: {
          0: "#FFFFFF",
          50: "#FAFAFA",
          100: "#EDEDED",
          200: "#D4D4D4",
          300: "#BBBCBC",
          400: "#A3A4A4",
          500: "#848585",
          600: "#717272",
          700: "#5E5F5F",
          800: "#454747",
          900: "#242626",
        },
      },
      boxShadow: {
        "offset-xs": "0 1px",
        "offset-sm": "0 2px",
        "offset-md": "0 4px",
        "offset-lg": "0 8px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", ...fontFamily.sans],
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
  ],
}
